name: PHP

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: ['7.3', '7.4']

    steps:
    - name: Install prerequesits
      run: sudo apt update && sudo apt install -y php-mbstring
    - uses: actions/checkout@v2
    - uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-versions }}
        extensions: mbstring
        tools: composer
    - name: Install dependencies
      run: |
        composer update 
        composer style
        composer install
    - name: Test
      run: composer test